### ISSUE TITLE
Hash external resources

### ISSUE THREAD

**Issue by iinfin** [macedigital/gulp-sri-hash#28]
It is specifically mentioned that "**`Referenced css- and js-files must be accessible from the local filesystem`**" but since it calculates based on the file content, shouldn't it also be possible to just read external file from url and generate hash?

I think integrity of external resources is more important as you have less control over them. So that would be a great option to have. Thanks.

**Comment by macedigital** [comment]
Hi, yes, technically, it is possible to calculate the content-hash of arbitrary network streams (excluding  network issues, etc).

Just so I understand the use-case, are you suggesting this plugin should add integrity-hashes for source files something like this?

```html
<html>
  <script src="http://external.domain.com/js/some-script.js">
  <link rel="stylesheet" href="//another.place.com/css/modal-in-css-only.css">
  <!-- other stuff -->
</html>
```

If so, I won't consider adding support for it, because it means you/I essentially vouch for arbitrary code / external resources we have no control over whatsoever.

Also, you could lock yourself out easily, whenever the contents of referenced files change (because someone elsewhere deployed a new version, deleted a file, etc.). 

Sub-resource hashing is a mechanism for giving users/consumers a way to verify the integrity of resources *you* as the producer of said file claim to have *full* control over. This is why external files should be validated by *their* respective producers, providing you/the browser with a checksum to test whether the respective file is valid after having received it.

**Comment by iinfin** [comment]
Yes that was the suggestion.

I thought not having control over those resources is actually one more reason to do it, to make sure you're requesting the intended file.

Some libraries already provide SRI hashes by default (like Bootstrap) but for others I have to use external services (like [report-uri.com](https://report-uri.com/home/sri_hash), or [srihash.org](https://www.srihash.org/)) which interrupts the workflow.

Also I think it doesn't have to mean locking yourself out if you're using it with specific versions from stable sources such as jsDelivr, Unpkg, cdnjs etc. It does kind of narrow down the use case, but I suppose that's usually the ideal way to follow, even though not widely practiced.

So wondered if that could at least be an option but thanks anyway.

**Comment by macedigital** [comment]
Thanks for bringing up the use-case. I agree that it can make sense if used very judiciously, but enabling downloads of external resources during build / watch time by default would create a number of new issues.

That being said, if you want to provide a PR for this feature with an explicit opt-in configuration flag, I won't stop you :smile:
